version: '3'
services:
  cronus:
    image: mattyp123/cronus:0.1.0
    ports:
      - "4000:4000"
    volumes:
      - ./config:/config
      - ./db:/db
    environment:
      - CUSTOM_CONFIG=/config/cronus.ini