# run this from nextjs (cronus) directory
run:
	export DEFAULT_CONFIG=./defaults/defaults.ini && \
	export CONFIG_PATH=./defaults && \
	export CUSTOM_CONFIG=../config/private.ini && \
	export OUTPUT_FILE=./.env.development && \
	export LOG_LEVEL=DEBUG && \
	export PORT=4001 && \
	npm run dev

