# run this from nextjs (cronus) directory
run:
	export DEFAULT_CONFIG=./defaults/defaults.ini && \
	export CONFIG_PATH=./defaults && \
	export CUSTOM_CONFIG=../config/dev.ini && \
	export OUTPUT_FILE=./development.env && \
	export PORT=4000 && \
	npm run dev

